name: Webex Notification

on:
  push:
    branches:
      - main

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webex Notification
        env:
          WEBEX_API_TOKEN: ${{ secrets.WEBEX_API_TOKEN }}
          ROOM_ID: "Y2lzY29zcGFyazovL3VybjpURUFNOmV1LWNlbnRyYWwtMV9rL1JPT00vYmQ3Y2Q3MzAtNTA4Mi0xMWVlLTg5OTEtNGI0YmRlNGYzNDcx"
        run: |
          curl -X POST "https://webexapis.com/v1/messages" \
            -H "Authorization: Bearer $WEBEX_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                "roomId": "'"$ROOM_ID"'",
                "text": "Hello from GitHub Actions!"
            }'
